ARG BUILD_FROM
FROM $BUILD_FROM

ARG BUILD_ARCH
ARG ARCH
RUN \
    CVERSION="latest/download" \
    $ARCH="${BUILD_ARCH}" \
    && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then $ARCH="arm64"; fi \
    && if [[ "${BUILD_ARCH}" = "amd64" ]]; then $ARCH="amd64"; fi \
    && if [[ "${BUILD_ARCH}" = "armhf" ]]; then $ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "armv7" ]]; then $ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "i386" ]]; then $ARCH="386"; fi \
    && apk add --no-cache libc6-compat yq \
    && wget -O /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/$CVERSION/cloudflared-linux-$ARCH && chmod +x /usr/local/bin/cloudflared

ENV TZ="Asia/Bangkok"
ENV CVERSION="latest/download"
ENV WOW=$ARCH

RUN cloudflared -v

COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]